baseURL = "https://mnaderib.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Mahdi Naderi"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80



[languages]

[languages.en]
Title = "Mahdi Naderi"
description = "PhD candidate at the Pattern Recognition Lab; \n TU Delft; Interested in Scientific Machine Learning"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[languages.fa]
Title = "مهدی نادری"
description = "دانشجوی دوره دکتری (یادگیری ماشین) \n گروه شناخت الگو و بیوانفورماتیک، دانشگاه صنعتی دلفت"
contentDir = "content/farsi" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "فارسی"