  [[main]]
  name = "خانه"
  identifier = "main"
  weight = 100
  url = "/fa/"

  [[main]]
  name = "نوشته ها"
  weight = 200
  identifier = "posts"
  url = "/fa/post/"

  [[main]]
  name = "درباره"
  weight = 300
  identifier = "about"
  url = "/fa/about/"

  [[main]]
  name = "تماس"
  weight = 400
  identifier = "contact"
  url = "/fa/contact/"