[en]
title = "Mahdi Naderi"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[fa]
title = "مهدی نادری"
description = "دانشجوی مقطع دکتری (یادگیری ماشین) \n گروه تشخیص الگو و بیوانفورماتیک، دانشگاه صنعتی دلفت"
contentDir = "content/farsi" 
weight = 1
LanguageDirection = "rtl" 
LanguageName = "پارسی"